const QUIZZES = [
  { topicId: 1, title: "Hola Mundo", questions: [
    { q: "¿Qué método imprime texto en la consola en Java?",
      opts: ["echo()", "console.log()", "System.out.println()", "print()"], correct: 2,
      exp: "System.out.println() es el método estándar para imprimir una línea en la consola Java." },
    { q: "En Java, el texto a imprimir debe estar entre comillas dobles.",
      opts: ["Verdadero", "Falso"], correct: 0,
      exp: "Los literales String usan comillas dobles. Las comillas simples están reservadas para char." },
    { q: "¿Qué imprimirá este código?", code: 'System.out.println("Java");',
      opts: ['"Java"', "Java", "Nothing is printed", 'System.out.println("Java")'], correct: 1,
      exp: "println imprime el texto sin las comillas que lo delimitan." },
    { q: 'Completa la sentencia: ___.out.println("Welcome!");',
      opts: ["Console", "Print", "System"], correct: 2,
      exp: "System es el objeto que contiene la salida estándar (out)." },
    { q: "Encuentra el error de sintaxis en la línea 3:", code: 'public class Main {\n    public static void main(String[] args) {\n        System.out.println(\'Hello World!\');\n    }\n}',
      opts: ["Falta el punto y coma", "El método se llama distinto", "Se usaron comillas simples en vez de dobles", "Falta la clase Main"], correct: 2,
      exp: "Los String deben ir entre comillas dobles. Las comillas simples son para char y solo admiten un carácter." },
  ]},
  { topicId: 2, title: "Variables numéricas", questions: [
    { q: "¿Qué almacena este código?", code: "double result = 7.5;",
      opts: ["0.0", "7", '"7.5"', "7.5"], correct: 3,
      exp: "El tipo double almacena números decimales, y 7.5 se asigna directamente a la variable." },
    { q: "¿Cuál es la declaración correcta para almacenar -15?",
      opts: ["double x = -15.0;", "int x = -15;", "number x = -15;", "INT x = -15;"], correct: 1,
      exp: "int almacena números enteros, incluyendo valores negativos como -15." },
    { q: "Una variable de tipo int puede almacenar el valor 3.14.",
      opts: ["Verdadero", "Falso"], correct: 1,
      exp: "int solo almacena enteros sin decimales. Para 3.14 se necesita double." },
    { q: "Encuentra el error de tipo en la declaración:", code: "quantity int = 10;",
      opts: ["Falta el punto y coma", "El tipo de dato debe ir antes del nombre", "int no puede almacenar 10", "Falta la palabra clave var"], correct: 1,
      exp: "La sintaxis correcta es: tipo nombre = valor; El tipo siempre va primero: int quantity = 10;" },
    { q: "¿Qué tipo se usa para declarar un precio de 49.99?",
      opts: ["Double", "int", "double", "Int"], correct: 2,
      exp: "double (en minúscula) es el tipo para números con punto decimal como precios." },
  ]},
  { topicId: 3, title: "Scanner", questions: [
    { q: "¿Qué clase de Java se usa para leer datos desde el teclado?",
      opts: ["Keyboard", "Input", "Scanner", "Reader"], correct: 2,
      exp: "Scanner es la clase del paquete java.util que permite leer la entrada estándar." },
    { q: "¿Qué import se necesita para usar Scanner?",
      opts: ["import java.io.Scanner;", "import java.util.Scanner;", "import java.Scanner;", "No necesita import"], correct: 1,
      exp: "Scanner pertenece al paquete java.util, por eso se importa con java.util.Scanner." },
    { q: "¿Qué argumento recibe new Scanner(___) para leer del teclado?",
      opts: ["System.out", "System.in", "new Keyboard()", '"teclado"'], correct: 1,
      exp: "System.in representa la entrada estándar (el teclado). System.out es la salida." },
    { q: "¿Qué método de Scanner lee una línea de texto completa?",
      opts: ["nextString()", "readLine()", "nextLine()", "getLine()"], correct: 2,
      exp: "nextLine() lee toda la línea que escribe el usuario hasta presionar Enter." },
    { q: "¿Qué método de Scanner se usa para leer un número entero?",
      opts: ["readInt()", "nextInt()", "getInt()", "scanInt()"], correct: 1,
      exp: "nextInt() lee el próximo token como entero. Para decimales se usa nextDouble()." },
  ]},
  { topicId: 4, title: "Variables de texto", questions: [
    { q: "¿Cuál declaración inicializa correctamente un String?",
      opts: ["String name = 'Hello';", 'string name = "Hello";', 'String name = "Hello";', "STRING name = Hello;"], correct: 2,
      exp: "String (con S mayúscula) usa comillas dobles. Las comillas simples son para char." },
    { q: "¿Qué tipo de dato es el valor 'b' (entre comillas simples)?",
      opts: ["boolean", "String", "char", "int"], correct: 2,
      exp: "Un solo carácter entre comillas simples representa un valor char." },
    { q: "¿Puede un char almacenar la cadena \"Hola\"?",
      opts: ["Sí, si la cadena es corta", "No, char solo contiene un carácter", "Sí, siempre", "Solo con comillas simples"], correct: 1,
      exp: "char solo puede contener exactamente un carácter. Para texto de varios caracteres se usa String." },
    { q: "¿Cuál es la declaración correcta de un char?",
      opts: ['char letra = "A";', "char letra = A;", "char letra = 'A';", "Char letra = 'A';"], correct: 2,
      exp: "char usa comillas simples y la palabra clave en minúscula: char letra = 'A';" },
    { q: "¿Qué operador se usa para concatenar Strings en Java?",
      opts: ["&", ".", "+", "*"], correct: 2,
      exp: "El operador + une (concatena) strings y variables: \"Hola, \" + nombre + \"!\"" },
  ]},
  { topicId: 5, title: "Operaciones aritméticas", questions: [
    { q: "¿Verdadero o Falso? La expresión double result = 5 + 3; almacenará 8.0.",
      opts: ["Verdadero", "Falso"], correct: 0,
      exp: "Cuando un resultado entero se asigna a una variable double, Java lo convierte automáticamente a 8.0." },
    { q: "¿Qué operador se usa para multiplicar en Java?",
      opts: ["x", "+", "*", "×"], correct: 2,
      exp: "El asterisco (*) es el operador de multiplicación en Java, no la letra x usada en matemáticas." },
    { q: "¿Qué valor tiene z?", code: "double x = 5.0;\ndouble y = 2.0;\ndouble z = x / y;",
      opts: ["2.0", "3.0", "2", "2.5"], correct: 3,
      exp: "La división entre doubles preserva los decimales: 5.0 / 2.0 = 2.5" },
    { q: "¿Cuál es el resultado de este código?", code: "int result = 10 / 4;",
      opts: ["2.5", "3", "2.0", "2"], correct: 3,
      exp: "La división entera entre int descarta los decimales: 10 / 4 = 2 (no 2.5)." },
    { q: "¿Qué devuelve el operador % (módulo)?",
      opts: ["El cociente de la división", "El porcentaje de un número", "El resto de la división", "Convierte a double"], correct: 2,
      exp: "El módulo devuelve el resto. Ejemplo: 10 % 3 = 1 (porque 10 = 3×3 + 1)." },
  ]},
  { topicId: 6, title: "Números Random", questions: [
    { q: "¿Qué import se necesita para usar la clase Random?",
      opts: ["import java.io.Random;", "import java.lang.Random;", "import java.util.Random;", "No necesita import"], correct: 2,
      exp: "Random pertenece al paquete java.util, igual que Scanner." },
    { q: "¿Qué devuelve rnd.nextInt(10)?",
      opts: ["Un entero entre 1 y 10", "Un entero entre 0 y 10", "Un entero entre 0 y 9", "Un double entre 0 y 10"], correct: 2,
      exp: "nextInt(n) devuelve un entero entre 0 y n-1. nextInt(10) da 0, 1, 2 … 9." },
    { q: "¿Qué produce este código?", code: "Random rnd = new Random();\nint dado = rnd.nextInt(6) + 1;",
      opts: ["Un entero entre 0 y 5", "Un entero entre 1 y 6", "Un entero entre 0 y 6", "Siempre el número 1"], correct: 1,
      exp: "nextInt(6) da 0–5, sumar 1 desplaza el rango a 1–6: perfecto para simular un dado." },
    { q: "¿Cuál es la fórmula para obtener un entero entre min y max (inclusive) con Random?",
      opts: ["rnd.nextInt(max) + min", "rnd.nextInt(max - min) + min", "rnd.nextInt(max - min + 1) + min", "rnd.nextInt(min) + max"], correct: 2,
      exp: "La fórmula es nextInt(max - min + 1) + min. Para 5–15: nextInt(11)+5 da 5, 6 … 15." },
    { q: "¿Qué método de Random genera un valor booleano aleatorio?",
      opts: ["nextBool()", "randomBoolean()", "nextBoolean()", "getBoolean()"], correct: 2,
      exp: "nextBoolean() devuelve true o false con igual probabilidad (50%)." },
  ]},
  { topicId: 7, title: "Condicional if / else", questions: [
    { q: "Con age=20, ¿cuál es el valor de status al terminar?", code: 'String status = "Child";\nif (age > 18) {\n    status = "Adult";\n}',
      opts: ["null", '"Child"', "Error de compilación", '"Adult"'], correct: 3,
      exp: "Como 20 > 18 es verdadero, se ejecuta el bloque y status pasa a valer \"Adult\"." },
    { q: "¿Qué ocurre cuando la condición del if evalúa a falso?",
      opts: ["El programa termina", "El bloque interno se omite y se continúa", "Se lanza un error", "El bloque se ejecuta igual"], correct: 1,
      exp: "Cuando la condición es falsa, todo el bloque dentro de las llaves se salta y el programa continúa." },
    { q: "¿Cuál es la sintaxis correcta del if?",
      opts: ["if condición { }", "IF (condición) { }", "if (condición) { }", "if [condición] { }"], correct: 2,
      exp: "La condición va entre paréntesis y el bloque entre llaves: if (condicion) { ... }" },
    { q: "El código ubicado fuera del bloque if siempre se ejecuta.",
      opts: ["Verdadero", "Falso"], correct: 0,
      exp: "El código fuera del bloque if { } corre siempre, sin importar si la condición fue verdadera o falsa." },
    { q: "Encuentra el error de sintaxis:", code: "if temp > 25 {\n    System.out.println(\"Calor\");\n}",
      opts: ["Falta punto y coma al final", "Faltan paréntesis alrededor de la condición", "El operador > es incorrecto", "Falta la palabra else"], correct: 1,
      exp: "La condición del if debe ir entre paréntesis: if (temp > 25) { ... }" },
  ]},
  { topicId: 8, title: "Bucle while", questions: [
    { q: "¿Cuándo se ejecuta el cuerpo de un bucle while?",
      opts: ["Siempre una vez como mínimo", "Mientras la condición sea verdadera", "Un número fijo de veces", "Solo si la condición es falsa"], correct: 1,
      exp: "El while verifica la condición antes de cada vuelta. Si es verdadera, ejecuta el bloque." },
    { q: "¿Qué ocurre si no se modifica la variable de control dentro del while?",
      opts: ["Se detiene a las 100 iteraciones", "Ocurre un bucle infinito", "Error de compilación", "Se ejecuta una sola vez"], correct: 1,
      exp: "Si la condición nunca pasa a falsa, el bucle se repite indefinidamente (bucle infinito)." },
    { q: "¿Cuántas veces se ejecuta este código?", code: "int i = 0;\nwhile (i < 3) {\n    i++;\n}",
      opts: ["1", "2", "4", "3"], correct: 3,
      exp: "i toma los valores 0, 1, 2. Cuando i=3 la condición i<3 es falsa y el bucle termina." },
    { q: "¿Qué imprime este código?", code: "int i = 1;\nwhile (i <= 3) {\n    System.out.println(i);\n    i++;\n}",
      opts: ["0 1 2", "1 2 3 4", "1 2 3", "0 1 2 3"], correct: 2,
      exp: "i empieza en 1 e imprime 1, 2, 3. Cuando i=4 la condición i<=3 es falsa y termina." },
    { q: "¿Cuál es la sintaxis correcta de while?",
      opts: ["while (x > 0)", "while x > 0", "while { x > 0 }", "while [x > 0]"], correct: 0,
      exp: "La condición va entre paréntesis: while (condicion) { ... }" },
  ]},
  { topicId: 9, title: "Bucle do-while", questions: [
    { q: "¿Cuál es la diferencia principal entre while y do-while?",
      opts: ["do-while es más rápido", "do-while ejecuta el cuerpo al menos una vez", "while siempre ejecuta más veces", "No hay diferencia"], correct: 1,
      exp: "El do-while verifica la condición después de ejecutar el bloque, por lo que siempre corre al menos una vez." },
    { q: "¿Dónde se escribe la condición en un do-while?",
      opts: ["Al inicio, antes del bloque", "Dentro del bloque", "Al final, después del bloque", "No lleva condición"], correct: 2,
      exp: "La sintaxis es: do { ... } while (condicion); La condición va al final con punto y coma." },
    { q: "¿Cuántas veces se ejecuta el cuerpo si la condición es falsa desde el inicio?", code: "int i = 10;\ndo {\n    System.out.println(i);\n    i++;\n} while (i < 5);",
      opts: ["0 veces", "1 vez", "Infinitas veces", "5 veces"], correct: 1,
      exp: "Aunque i=10 no cumple i<5, el do-while ejecuta el bloque una vez antes de verificar." },
    { q: "¿Qué imprime este código?", code: "int i = 1;\ndo {\n    System.out.println(i);\n    i++;\n} while (i <= 3);",
      opts: ["1 2 3 4", "0 1 2 3", "1 2 3", "2 3"], correct: 2,
      exp: "i empieza en 1 e imprime 1, 2, 3. Cuando i=4 la condición i<=3 es falsa y termina." },
    { q: "¿Cuál es la sintaxis correcta del do-while?",
      opts: ["do { } while condicion;", "do { } while (condicion)", "do { } while (condicion);", "while (condicion) do { }"], correct: 2,
      exp: "La sintaxis correcta es: do { ... } while (condicion); — con paréntesis y punto y coma al final." },
  ]},
  { topicId: 10, title: "Bucle for", questions: [
    { q: "¿Qué error tiene este for?", code: "for (int i = 0, i < 5, i++) {\n    System.out.println(i);\n}",
      opts: ["La variable i no está declarada", "Las comas deben ser punto y coma", "La condición debería usar <=", "Faltan llaves"], correct: 1,
      exp: "Las tres partes del encabezado del for se separan con punto y coma: for (int i=0; i<5; i++)" },
    { q: "¿Qué imprime este bucle?", code: "for (int i = 2; i < 5; i++) {\n    System.out.println(i);\n}",
      opts: ["0 1 2 3 4", "2 3 4 5", "1 2 3 4", "2 3 4"], correct: 3,
      exp: "i empieza en 2 y la condición i<5 excluye el 5. Se imprime 2, 3, 4." },
    { q: "¿Cuántas veces se ejecuta este bucle?", code: "for (int i = 0; i < 5; i++) {\n    System.out.println(\"Hola\");\n}",
      opts: ["4", "6", "5", "3"], correct: 2,
      exp: "i toma los valores 0, 1, 2, 3, 4 — cinco valores en total antes de que i<5 sea falso." },
    { q: "La expresión de actualización (i++) se ejecuta después de cada iteración del cuerpo.",
      opts: ["Verdadero", "Falso"], correct: 0,
      exp: "i++ se ejecuta al final de cada vuelta, antes de volver a verificar la condición." },
    { q: "¿Qué valores completan este for para iterar del 1 al 10 incluyendo el 10?", code: "for (int i = ___; i ___ 10; i++) { }",
      opts: ["i=0 y i<10", "i=1 y i<=10", "i=1 y i<10", "i=0 y i<=10"], correct: 1,
      exp: "Para incluir el 10 se usa <= con inicio en 1. Con i<10 solo llegaría hasta 9." },
  ]},
  { topicId: 11, title: "Procedimientos", questions: [
    { q: "¿Qué palabra clave indica que un método no devuelve ningún valor?",
      opts: ["return", "null", "void", "empty"], correct: 2,
      exp: "void significa que el método realiza una tarea pero no retorna ningún valor al código que lo llamó." },
    { q: "¿Cuál es la sintaxis correcta para declarar un procedimiento sin parámetros?",
      opts: ["void static saludar() { }", "static void saludar() { }", "static saludar void() { }", "void saludar static() { }"], correct: 1,
      exp: "El orden correcto es: static void nombreMetodo() { ... }" },
    { q: "¿Cuántas veces se puede llamar a un procedimiento desde main?",
      opts: ["Solo una vez", "Máximo dos veces", "Las veces que sea necesario", "Depende del tipo de retorno"], correct: 2,
      exp: "Una de las ventajas de los procedimientos es que se pueden llamar múltiples veces sin repetir el código." },
    { q: "¿Qué hace este código?", code: "static void linea() {\n    System.out.println(\"-----\");\n}\n// en main:\nlinea();\nlinea();",
      opts: ["Imprime ----- una sola vez", "Genera un error porque se llama dos veces", "Imprime ----- dos veces", "No imprime nada"], correct: 2,
      exp: "Cada llamada a linea() ejecuta el cuerpo completo del procedimiento, imprimiendo ----- una vez por llamada." },
    { q: "¿Qué son los parámetros de un procedimiento?",
      opts: ["Variables que se declaran dentro del procedimiento", "Datos que se pasan al procedimiento cuando se lo llama", "El valor que retorna el procedimiento", "Los nombres de las clases que usa el procedimiento"], correct: 1,
      exp: "Los parámetros son los datos de entrada que recibe el procedimiento para trabajar con ellos." },
  ]},
  { topicId: 12, title: "Funciones", questions: [
    { q: "¿En qué se diferencia una función de un procedimiento?",
      opts: ["Una función usa static y un procedimiento no", "Una función devuelve un valor y un procedimiento no", "Una función puede tener parámetros y un procedimiento no", "No hay diferencia"], correct: 1,
      exp: "La diferencia clave es el valor de retorno: las funciones usan return para devolver un resultado; los procedimientos usan void." },
    { q: "¿Qué palabra clave se usa para devolver un valor desde una función?",
      opts: ["send", "output", "give", "return"], correct: 3,
      exp: "return envía el valor de vuelta al código que llamó a la función y termina la ejecución del método." },
    { q: "¿Cuál declara correctamente una función que retorna un entero?",
      opts: ["static void sumar(int a, int b) { }", "static int sumar(int a, int b) { }", "int static sumar(int a, int b) { }", "static sumar int(int a, int b) { }"], correct: 1,
      exp: "El tipo de retorno va después de static y antes del nombre: static int nombreFuncion(...) { }" },
    { q: "¿Qué almacena la variable resultado?", code: "static int doble(int n) {\n    return n * 2;\n}\nint resultado = doble(5);",
      opts: ["5", "2", "52", "10"], correct: 3,
      exp: "La función retorna n * 2, y como se la llama con 5, devuelve 10. Ese valor se guarda en resultado." },
    { q: "¿Qué ocurre si una función declarada como int no tiene ningún return?",
      opts: ["Retorna 0 automáticamente", "Error de compilación", "Retorna null", "El programa se detiene en tiempo de ejecución"], correct: 1,
      exp: "Java exige que todos los caminos de ejecución de una función lleguen a un return del tipo declarado; si no, el compilador da error." },
  ]},
  { topicId: 13, title: "Arrays", questions: [
    { q: "¿Qué delimitadores se usan para inicializar un array con valores?", code: 'String[] names = ___"Alice", "Bob", "Charlie"___;',
      opts: ["( y )", "[ y ]", "{ y }", "< y >"], correct: 2,
      exp: "Las llaves { } se usan para inicializar un array con valores directos al declararlo." },
    { q: "¿Verdadero o Falso? numbers.length() devuelve el número de elementos del array.",
      opts: ["Verdadero", "Falso"], correct: 1,
      exp: "Es numbers.length sin paréntesis. length es un campo (atributo), no un método." },
    { q: "¿Qué valor almacena size?", code: "int[] scores = {10, 20, 30, 40};\nint size = scores.length;",
      opts: ["40", "3", "0", "4"], correct: 3,
      exp: "length devuelve la cantidad de elementos del array. scores tiene 4 elementos." },
    { q: "¿Qué imprime este código?", code: "int[] n = new int[3];\nSystem.out.println(n[0]);",
      opts: ["null", "Error de compilación", "3", "0"], correct: 3,
      exp: "Los arrays de int se inicializan con 0 por defecto cuando se crean con new int[size]." },
    { q: "¿Qué índice tiene el ÚLTIMO elemento de un array de 5 elementos?",
      opts: ["5", "4", "1", "0"], correct: 1,
      exp: "Los índices van de 0 a length-1. En un array de 5 elementos el último tiene índice 4." },
  ]},
  { topicId: 14, title: "Comentarios", questions: [
    { q: "¿Qué símbolo se usa para iniciar un comentario de una sola línea en Java?",
      opts: ["//", "/*", "#", "<!--"], correct: 0,
      exp: "// indica un comentario de una línea. Todo lo que sigue en esa línea es ignorado por el compilador." },
    { q: "Los comentarios afectan la ejecución del programa.",
      opts: ["Verdadero", "Falso"], correct: 1,
      exp: "Los comentarios son ignorados por el compilador. No generan código ni afectan el comportamiento del programa." },
    { q: "¿Qué delimitadores forman un comentario de bloque en Java?",
      opts: ["// y //", "/* y */", "<!-- y -->", "# y #"], correct: 1,
      exp: "Los comentarios de bloque comienzan con /* y terminan con */. Pueden abarcar múltiples líneas." },
    { q: "¿Cuál de estos es un comentario válido en Java?",
      opts: ["# Este es un comentario", "// Este es un comentario", "-- Este es un comentario", "** Este es un comentario"], correct: 1,
      exp: "Java usa // para comentarios de una línea y /* ... */ para bloques. No usa # ni --." },
    { q: "¿Para qué sirven principalmente los comentarios?",
      opts: ["Para ejecutar código alternativo", "Para documentar y explicar el código", "Para aumentar la velocidad del programa", "Para declarar variables"], correct: 1,
      exp: "Los comentarios sirven para documentar el código: explicar qué hace, por qué se tomó una decisión, o dejar notas para otros programadores." },
  ]},
  { topicId: 15, title: "Constantes", questions: [
    { q: "¿Qué palabra clave se usa en Java para declarar una constante?",
      opts: ["const", "constant", "final", "static"], correct: 2,
      exp: "final indica que el valor no puede cambiar después de ser asignado. Es la forma estándar de declarar constantes en Java." },
    { q: "¿Qué ocurre si se intenta reasignar el valor de una constante?",
      opts: ["El nuevo valor se ignora silenciosamente", "El programa continúa con el valor original", "Error de compilación", "Error en tiempo de ejecución"], correct: 2,
      exp: "Java no compila un programa que intente modificar una variable declarada con final. El error aparece en tiempo de compilación." },
    { q: "¿Cuál es la convención de nombres para constantes en Java?",
      opts: ["camelCase como las variables", "PascalCase como las clases", "MAYÚSCULAS_CON_GUIÓN_BAJO", "minúsculas con puntos"], correct: 2,
      exp: "Por convención, las constantes se escriben en MAYÚSCULAS con guiones bajos entre palabras: MAX_SIZE, TASA_IVA, PI." },
    { q: "¿Cuál es la declaración correcta de una constante entera?",
      opts: ["const int MAX = 100;", "int final MAX = 100;", "final int MAX = 100;", "FINAL int MAX = 100;"], correct: 2,
      exp: "La sintaxis es: final tipo NOMBRE = valor; La palabra final va antes del tipo." },
    { q: "¿Cuál es la principal ventaja de usar constantes con nombre en lugar de valores literales?",
      opts: ["Ocupan menos memoria", "Facilitan cambios y mejoran la legibilidad", "Ejecutan más rápido", "No hay diferencia"], correct: 1,
      exp: "Las constantes con nombre expresan la intención del valor y permiten cambiarlo en un solo lugar si es necesario." },
  ]},
  { topicId: 16, title: "Conversión de tipos", questions: [
    { q: "¿Qué es la conversión implícita (widening) en Java?",
      opts: ["Convertir un tipo grande a uno pequeño", "Convertir un tipo pequeño a uno más grande automáticamente", "Convertir String a int", "Usar el operador cast"], correct: 1,
      exp: "Widening convierte automáticamente de un tipo más pequeño a uno mayor (int → double) sin pérdida de datos." },
    { q: "¿Qué produce la expresión (int) 3.9?",
      opts: ["4", "3", "Error de compilación", "3.9"], correct: 1,
      exp: "El cast (int) trunca los decimales: simplemente los descarta. 3.9 se convierte en 3 (no redondea)." },
    { q: "¿Qué tipo de conversión requiere un cast explícito?",
      opts: ["int a long", "int a double", "double a int", "int a float"], correct: 2,
      exp: "Narrowing (de double a int) requiere cast explícito: (int) valor. Puede haber pérdida de información." },
    { q: "¿Qué imprime este código?", code: "int a = 5;\ndouble b = a;\nSystem.out.println(b);",
      opts: ["5", "5.0", "Error", "0.0"], correct: 1,
      exp: "Java convierte int a double automáticamente (widening). El valor 5 se representa como 5.0." },
    { q: "¿Qué devuelve la expresión (double) 7 / 2?",
      opts: ["3", "3.0", "3.5", "Error"], correct: 2,
      exp: "(double) 7 convierte el 7 a 7.0 antes de dividir. 7.0 / 2 da 3.5 porque ya hay un double involucrado." },
  ]},
  { topicId: 17, title: "Incremento y decremento", questions: [
    { q: "¿Qué hace el operador ++ aplicado a una variable entera?",
      opts: ["La multiplica por 2", "La incrementa en 1", "La decrementa en 1", "La convierte a double"], correct: 1,
      exp: "++ incrementa la variable en 1. i++ es equivalente a escribir i = i + 1." },
    { q: "Con i = 5, ¿qué valor se asigna a x en la expresión x = i++?",
      opts: ["6", "5", "4", "Error"], correct: 1,
      exp: "Post-incremento (i++): primero se asigna el valor actual (5) a x, luego se incrementa i a 6." },
    { q: "Con i = 5, ¿qué valor se asigna a x en la expresión x = ++i?",
      opts: ["4", "5", "6", "Error"], correct: 2,
      exp: "Pre-incremento (++i): primero se incrementa i a 6, luego se asigna ese valor a x." },
    { q: "¿Cuánto vale i después de ejecutar i-- si i comenzaba en 3?",
      opts: ["4", "3", "2", "1"], correct: 2,
      exp: "-- decrementa la variable en 1: 3 - 1 = 2." },
    { q: "¿Qué operador es equivalente a i = i - 1?",
      opts: ["i++", "i--", "++i", "i+=1"], correct: 1,
      exp: "i-- decrementa i en 1, igual que escribir i = i - 1." },
  ]},
  { topicId: 18, title: "Atajos aritméticos", questions: [
    { q: "¿A qué es equivalente la expresión x += 5?",
      opts: ["x = 5", "x = x + 5", "x = x * 5", "x + 5"], correct: 1,
      exp: "+= es un atajo: x += 5 es lo mismo que x = x + 5. Suma el valor derecho al actual de x." },
    { q: "Si x = 10, ¿cuánto vale x después de x -= 3?",
      opts: ["13", "7", "3", "30"], correct: 1,
      exp: "x -= 3 es x = x - 3 = 10 - 3 = 7." },
    { q: "Si x = 4, ¿cuánto vale x después de x *= 2?",
      opts: ["2", "6", "8", "4"], correct: 2,
      exp: "x *= 2 es x = x * 2 = 4 * 2 = 8." },
    { q: "¿Cuál es el atajo para x = x / 2?",
      opts: ["x /= 2", "x div= 2", "x //= 2", "x \\= 2"], correct: 0,
      exp: "/= divide el valor actual de x por el operando derecho: x /= 2 equivale a x = x / 2." },
    { q: "Si x = 10, ¿cuánto vale x después de x %= 3?",
      opts: ["3", "10", "1", "0"], correct: 2,
      exp: "%= aplica el módulo: x %= 3 es x = 10 % 3 = 1 (el resto de dividir 10 entre 3)." },
  ]},
  { topicId: 19, title: "Operadores de comparación", questions: [
    { q: "¿Qué devuelve la expresión 5 == 5?",
      opts: ["5", "true", "false", "Error"], correct: 1,
      exp: "== compara si dos valores son iguales y devuelve un boolean: true si son iguales, false si no." },
    { q: "¿Cuál operador comprueba si dos valores son distintos?",
      opts: ["=", "==", "!=", "<>"], correct: 2,
      exp: "!= devuelve true cuando los valores son distintos. Es el opuesto de ==." },
    { q: "¿Qué devuelve la expresión 3 >= 3?",
      opts: ["false", "true", "0", "Error"], correct: 1,
      exp: ">= devuelve true si el valor izquierdo es mayor O igual al derecho. 3 >= 3 es true porque son iguales." },
    { q: "¿Cuál es el resultado de 10 < 5?",
      opts: ["true", "false", "10", "5"], correct: 1,
      exp: "10 no es menor que 5, por lo tanto 10 < 5 es false." },
    { q: "Los operadores de comparación siempre devuelven un valor de tipo...",
      opts: ["int", "String", "double", "boolean"], correct: 3,
      exp: "Los operadores de comparación (==, !=, >, <, >=, <=) siempre producen un valor boolean: true o false." },
  ]},
  { topicId: 20, title: "Operadores lógicos", questions: [
    { q: "¿Cuándo es verdadera la expresión A && B?",
      opts: ["Cuando A es true", "Cuando B es true", "Cuando A y B son ambos true", "Cuando al menos uno es true"], correct: 2,
      exp: "&& (AND) solo devuelve true cuando AMBOS operandos son true. Si cualquiera es false, el resultado es false." },
    { q: "¿Cuándo es verdadera la expresión A || B?",
      opts: ["Solo cuando ambos son true", "Cuando al menos uno es true", "Solo cuando ambos son false", "Nunca"], correct: 1,
      exp: "|| (OR) devuelve true cuando AL MENOS UNO de los operandos es true. Solo es false cuando ambos son false." },
    { q: "¿Qué devuelve !true?",
      opts: ["true", "1", "false", "0"], correct: 2,
      exp: "! (NOT) invierte el valor booleano: !true es false, !false es true." },
    { q: "Con a = true y b = false, ¿qué devuelve a && b?",
      opts: ["true", "false", "null", "Error"], correct: 1,
      exp: "a && b requiere que ambos sean true. Como b es false, el resultado es false." },
    { q: "Con a = true y b = false, ¿qué devuelve a || b?",
      opts: ["false", "true", "null", "Error"], correct: 1,
      exp: "a || b requiere que al menos uno sea true. Como a es true, el resultado es true." },
  ]},
  { topicId: 21, title: "System.out.print", questions: [
    { q: "¿Cuál es la diferencia entre System.out.print() y System.out.println()?",
      opts: ["print imprime en rojo, println en negro", "println agrega un salto de línea al final, print no", "print es más rápido que println", "No hay diferencia"], correct: 1,
      exp: "println (print line) agrega automáticamente un salto de línea al final. print imprime sin avanzar al siguiente renglón." },
    { q: "¿Qué produce la secuencia de escape \\n dentro de un String?",
      opts: ["Imprime la letra n", "Una tabulación", "Un salto de línea", "Un espacio en blanco"], correct: 2,
      exp: "\\n es la secuencia de escape para salto de línea. Permite insertar saltos dentro de un solo String." },
    { q: "¿Qué produce la secuencia de escape \\t dentro de un String?",
      opts: ["Un salto de línea", "Una tabulación horizontal", "La letra t", "El carácter de retroceso"], correct: 1,
      exp: "\\t inserta una tabulación horizontal, equivalente a presionar Tab en el teclado." },
    { q: "¿Cómo se imprime una comilla doble dentro de un String?",
      opts: ["Usando comillas simples dentro", "Usando la secuencia \\\"", "No es posible", "Usando doble comilla \"\""], correct: 1,
      exp: "\\\" es la secuencia de escape para una comilla doble dentro de un String delimitado por comillas dobles." },
    { q: "¿Qué imprime este código?", code: 'System.out.print("A");\nSystem.out.print("B");',
      opts: ["A B", "A\\nB", "AB", "A y luego B en línea nueva"], correct: 2,
      exp: "print no agrega salto de línea, por lo que ambas impresiones quedan en la misma línea: AB." },
  ]},
  { topicId: 22, title: "Formato de salida", questions: [
    { q: "¿Qué método permite imprimir con formato usando especificadores como %d y %s?",
      opts: ["System.out.println()", "System.out.format()", "System.out.printf()", "String.print()"], correct: 2,
      exp: "printf permite controlar el formato de la salida usando especificadores como %d (entero), %s (String), %f (decimal)." },
    { q: "¿Qué especificador de formato se usa para imprimir un número entero?",
      opts: ["%s", "%f", "%d", "%i"], correct: 2,
      exp: "%d formatea un número entero (int, long). Ejemplo: printf(\"%d\", 42) imprime 42." },
    { q: "¿Qué especificador de formato se usa para imprimir un String?",
      opts: ["%d", "%s", "%c", "%f"], correct: 1,
      exp: "%s formatea un String. Ejemplo: printf(\"Hola, %s!\", nombre) inserta el valor de nombre." },
    { q: "¿Qué hace el especificador %.2f?",
      opts: ["Muestra 2 dígitos en total", "Muestra exactamente 2 decimales", "Muestra el número en base 2", "Muestra 2 enteros y decimales libres"], correct: 1,
      exp: "%.2f formatea un número de punto flotante con exactamente 2 decimales. 3.14159 se muestra como 3.14." },
    { q: "¿Qué imprime printf(\"%.1f\", 3.456)?",
      opts: ["3", "3.4", "3.5", "3.456"], correct: 2,
      exp: "%.1f muestra 1 decimal y redondea. 3.456 redondeado a 1 decimal es 3.5." },
  ]},
  { topicId: 23, title: "Switch", questions: [
    { q: "¿Qué sentencia se usa al final de cada case para evitar que la ejecución continúe al siguiente?",
      opts: ["return", "stop", "break", "end"], correct: 2,
      exp: "break detiene la ejecución del switch y salta al código que sigue. Sin break, se ejecutan todos los case siguientes (fall-through)." },
    { q: "¿Cuándo se ejecuta el bloque default en un switch?",
      opts: ["Siempre, antes de los case", "Siempre, después de los case", "Cuando ningún case coincide con el valor", "Nunca es ejecutado"], correct: 2,
      exp: "default es el caso por defecto: se ejecuta cuando ningún case coincide con el valor evaluado." },
    { q: "¿Cuáles de estos tipos puede evaluar un switch en Java?",
      opts: ["Solo int", "int, String y char", "Solo String", "double y float"], correct: 1,
      exp: "Switch puede evaluar int, char, String y tipos discretos. No puede evaluar double ni float." },
    { q: "¿Es obligatorio incluir un bloque default en un switch?",
      opts: ["Sí, siempre es obligatorio", "No, es opcional", "Solo si hay más de 3 casos", "Solo cuando se evalúan Strings"], correct: 1,
      exp: "default es opcional. El programa compila y ejecuta correctamente sin él, pero es buena práctica incluirlo." },
    { q: "¿Qué ocurre si un case no tiene break?", code: 'int x = 1;\nswitch (x) {\n    case 1: System.out.println("Uno");\n    case 2: System.out.println("Dos");\n    default: System.out.println("Otro");\n}',
      opts: ["Solo imprime Uno", "Imprime Uno y se detiene", "Imprime Uno, Dos y Otro", "Error de compilación"], correct: 2,
      exp: "Sin break ocurre fall-through: una vez que coincide un case, se ejecutan todos los bloques siguientes hasta el final del switch." },
  ]},
  { topicId: 24, title: "Operador ternario", questions: [
    { q: "¿Cuál es la sintaxis correcta del operador ternario?",
      opts: ["condicion : valorSi ? valorNo", "condicion ? valorSi : valorNo", "if condicion ? valorSi : valorNo", "condicion ?? valorSi : valorNo"], correct: 1,
      exp: "La sintaxis es: condicion ? expresionSiVerdadero : expresionSiFalso. Es como un if/else compacto en una expresión." },
    { q: "¿Qué devuelve la expresión (5 > 3) ? \"mayor\" : \"menor\"?",
      opts: ['"menor"', '"true"', '"mayor"', '"5 > 3"'], correct: 2,
      exp: "5 > 3 es true, por lo tanto se evalúa y devuelve la expresión del lado del ?: \"mayor\"." },
    { q: "¿Cuántos valores produce un operador ternario en cada evaluación?",
      opts: ["Cero o uno", "Siempre exactamente uno", "Uno o dos", "Depende de la condición"], correct: 1,
      exp: "El ternario siempre produce exactamente un valor: el de la expresión verdadera o el de la falsa, según la condición." },
    { q: "Un operador ternario puede reemplazar a un if/else simple.",
      opts: ["Verdadero", "Falso"], correct: 0,
      exp: "Verdadero. String r = (nota >= 60) ? \"Aprobado\" : \"Reprobado\"; es equivalente a un if/else que asigna a r." },
    { q: "Con x = 0, ¿qué devuelve: (x > 0) ? \"positivo\" : \"no positivo\"?",
      opts: ['"positivo"', '"no positivo"', '"true"', '"false"'], correct: 1,
      exp: "0 > 0 es false, por lo que se evalúa la expresión del lado del :: \"no positivo\"." },
  ]},
  { topicId: 25, title: "Comparación de Strings", questions: [
    { q: "¿Por qué no se recomienda usar == para comparar el contenido de dos Strings?",
      opts: ["Porque == no funciona con Strings", "Porque == compara las referencias en memoria, no el contenido", "Porque == es más lento", "Porque Java no tiene =="], correct: 1,
      exp: "== compara si dos variables apuntan al mismo objeto en memoria. Dos String con el mismo texto pueden ser objetos distintos, así que == podría devolver false aunque el contenido sea igual." },
    { q: "¿Qué método compara el contenido de dos Strings ignorando mayúsculas y minúsculas?",
      opts: ["equals()", "compareTo()", "equalsIgnoreCase()", "compareIgnoreCase()"], correct: 2,
      exp: "equalsIgnoreCase() compara el contenido sin distinguir entre mayúsculas y minúsculas: \"Hola\".equalsIgnoreCase(\"hola\") devuelve true." },
    { q: "¿Qué devuelve \"hola\".equals(\"hola\")?",
      opts: ["false", "null", "true", "0"], correct: 2,
      exp: "equals() compara el contenido carácter a carácter. Como ambos Strings contienen \"hola\", devuelve true." },
    { q: "¿Qué devuelve \"abc\".equals(\"ABC\")?",
      opts: ["true", "false", "null", "Error"], correct: 1,
      exp: "equals() distingue mayúsculas de minúsculas. \"abc\" y \"ABC\" tienen contenido diferente, por lo que devuelve false." },
    { q: "¿Cuál es la forma correcta de comparar si dos variables String tienen el mismo contenido?",
      opts: ["s1 == s2", "s1.equals(s2)", "s1 = s2", "equals(s1, s2)"], correct: 1,
      exp: "s1.equals(s2) es la forma correcta: llama al método equals() sobre uno de los Strings pasando el otro como argumento." },
  ]},
  { topicId: 26, title: "Métodos de String", questions: [
    { q: "¿Qué devuelve \"Hola\".length()?",
      opts: ["3", "4", "5", "Error"], correct: 1,
      exp: "length() devuelve la cantidad de caracteres del String. \"Hola\" tiene 4 caracteres: H-o-l-a." },
    { q: "¿Qué devuelve \"Java\".charAt(0)?",
      opts: ["'a'", "'J'", "'v'", "\"Java\""], correct: 1,
      exp: "charAt(n) devuelve el carácter en la posición n. Los índices empiezan en 0, por lo que charAt(0) devuelve 'J'." },
    { q: "¿Qué devuelve \"Mundo\".substring(0, 3)?",
      opts: ['"Mun"', '"und"', '"Mund"', '"Mundo"'], correct: 0,
      exp: "substring(inicio, fin) extrae desde inicio (inclusive) hasta fin (exclusive). Posiciones 0, 1, 2 → \"Mun\"." },
    { q: "¿Qué hace el método toUpperCase()?",
      opts: ["Convierte el primer carácter a mayúscula", "Convierte todos los caracteres a mayúscula", "Convierte a minúsculas", "Elimina los espacios"], correct: 1,
      exp: "toUpperCase() devuelve un nuevo String con todos los caracteres convertidos a mayúsculas. Ejemplo: \"hola\".toUpperCase() → \"HOLA\"." },
    { q: "¿Qué devuelve \"hola mundo\".contains(\"mundo\")?",
      opts: ["false", "null", "true", "Error"], correct: 2,
      exp: "contains() devuelve true si el String contiene la secuencia de caracteres especificada. \"hola mundo\" sí contiene \"mundo\"." },
  ]},
  { topicId: 27, title: "Break y Continue", questions: [
    { q: "¿Qué hace la sentencia break dentro de un bucle?",
      opts: ["Salta la iteración actual y continúa", "Pausa el bucle temporalmente", "Termina el bucle inmediatamente", "Reinicia el bucle desde el inicio"], correct: 2,
      exp: "break termina el bucle de inmediato. La ejecución continúa con el código que está después del cierre del bucle." },
    { q: "¿Qué hace la sentencia continue dentro de un bucle?",
      opts: ["Termina el bucle", "Salta el resto de la iteración actual y pasa a la siguiente", "Reinicia el contador a 0", "Sale del método"], correct: 1,
      exp: "continue salta el resto del cuerpo de la iteración actual y vuelve al inicio del bucle para evaluar la condición nuevamente." },
    { q: "¿En cuál de estas estructuras también funciona la sentencia break?",
      opts: ["Métodos", "Switch", "Clases", "Variables"], correct: 1,
      exp: "break funciona en bucles (for, while, do-while) y también en la sentencia switch para evitar el fall-through." },
    { q: "¿Qué imprime este código?", code: "for (int i = 1; i <= 5; i++) {\n    if (i == 3) break;\n    System.out.println(i);\n}",
      opts: ["1 2 3", "1 2", "3 4 5", "1 2 3 4 5"], correct: 1,
      exp: "Cuando i vale 3, break termina el bucle. Solo se imprimen los valores 1 y 2." },
    { q: "¿Qué imprime este código?", code: "for (int i = 1; i <= 5; i++) {\n    if (i == 3) continue;\n    System.out.println(i);\n}",
      opts: ["1 2 3 4 5", "1 2 4 5", "3", "1 2"], correct: 1,
      exp: "Cuando i vale 3, continue salta el println. Se imprimen todos los valores excepto el 3: 1, 2, 4, 5." },
  ]},
  { topicId: 28, title: "Bucles anidados", questions: [
    { q: "¿Cuántas veces se ejecuta el cuerpo del bucle interno en este código?", code: "for (int i = 0; i < 3; i++) {\n    for (int j = 0; j < 3; j++) {\n        // cuerpo\n    }\n}",
      opts: ["3", "6", "9", "12"], correct: 2,
      exp: "El bucle externo se ejecuta 3 veces y por cada vuelta el interno se ejecuta 3 veces. Total: 3 × 3 = 9." },
    { q: "¿Por qué es importante usar variables de control distintas en bucles anidados?",
      opts: ["Por una restricción del compilador", "Para que cada bucle controle su propia iteración sin interferir", "Porque es más rápido", "No es necesario"], correct: 1,
      exp: "Si ambos bucles usaran la misma variable, se pisarían entre sí y el comportamiento sería incorrecto." },
    { q: "¿Para qué situación son más útiles los bucles anidados?",
      opts: ["Para sumar una lista de números", "Para trabajar con estructuras bidimensionales como tablas o matrices", "Para leer datos del usuario", "Para declarar variables"], correct: 1,
      exp: "Los bucles anidados son ideales para recorrer estructuras de dos dimensiones: tablas, matrices, o para generar patrones de filas y columnas." },
    { q: "Con for i de 0 a 1 y for j de 0 a 2, ¿cuántas iteraciones totales ejecuta el cuerpo interno?",
      opts: ["2", "3", "5", "6"], correct: 3,
      exp: "El externo da 2 vueltas (i: 0, 1), el interno da 3 vueltas (j: 0, 1, 2). Total: 2 × 3 = 6 iteraciones." },
    { q: "¿Qué imprime este código?", code: "for (int i = 1; i <= 2; i++) {\n    for (int j = 1; j <= 2; j++) {\n        System.out.print(i + \"\" + j + \" \");\n    }\n}",
      opts: ["11 12 21 22", "1 2 1 2", "11 22", "12 12"], correct: 0,
      exp: "El bucle externo controla i (1, 2) y el interno j (1, 2). Se imprime la combinación para cada par: 11 12 21 22." },
  ]},
  { topicId: 29, title: "Sobrecarga de métodos", questions: [
    { q: "¿Qué es la sobrecarga de métodos (method overloading)?",
      opts: ["Llamar a un método más de una vez", "Tener varios métodos con el mismo nombre pero distintos parámetros", "Heredar un método de otra clase", "Usar static en un método"], correct: 1,
      exp: "La sobrecarga permite definir varios métodos con el mismo nombre siempre que difieran en el número o tipo de parámetros." },
    { q: "¿Pueden existir dos métodos con el mismo nombre y parámetros pero distinto tipo de retorno?",
      opts: ["Sí, siempre", "No, el compilador no lo permite", "Sí, si uno es static", "Depende del compilador"], correct: 1,
      exp: "No es posible. El compilador identifica un método por su nombre y sus parámetros (firma). El tipo de retorno no forma parte de la firma." },
    { q: "¿Cuál par de declaraciones es una sobrecarga válida?",
      opts: ["static void f(int x) y static void f(int y)", "static void f(int x) y static void f(double x)", "static int f(int x) y static void f(int x)", "Ninguna"], correct: 1,
      exp: "Cambiar el tipo de parámetro (int vs double) sí constituye sobrecarga válida. Cambiar solo el nombre del parámetro o el tipo de retorno no." },
    { q: "¿En qué momento decide Java qué versión sobrecargada de un método llamar?",
      opts: ["En tiempo de ejecución", "En tiempo de compilación", "Cuando se importa la clase", "Cuando se crea el objeto"], correct: 1,
      exp: "La resolución de sobrecarga ocurre en tiempo de compilación: el compilador analiza los argumentos y elige la versión del método que mejor coincide." },
    { q: "¿Cuántas versiones sobrecargadas puede tener un método en Java?",
      opts: ["Máximo 3", "Máximo 10", "Solo 2", "Sin límite fijo"], correct: 3,
      exp: "No hay un límite de cuántas versiones sobrecargadas puede tener un método, siempre que cada una tenga una firma diferente." },
  ]},
  { topicId: 30, title: "Proyecto Calculadora", questions: [
    { q: "¿Cuál es la forma correcta de leer un número decimal con Scanner?",
      opts: ["sc.nextDecimal()", "sc.nextDouble()", "sc.nextFloat()", "sc.readDouble()"], correct: 1,
      exp: "nextDouble() es el método de Scanner para leer un número con punto decimal (double)." },
    { q: "¿Qué estructura de control es más adecuada para elegir una operación según un carácter (+, -, *, /)?",
      opts: ["while", "for", "switch", "do-while"], correct: 2,
      exp: "switch con un char o String de operador es la estructura más clara para elegir entre un conjunto fijo de opciones." },
    { q: "¿Qué verificación se debe hacer antes de dividir para evitar un error?",
      opts: ["Verificar que el dividendo no sea 0", "Verificar que el divisor no sea 0", "Usar try-catch obligatoriamente", "No es necesario verificar"], correct: 1,
      exp: "Dividir por cero lanza una ArithmeticException. Se debe verificar que el divisor != 0 antes de realizar la división." },
    { q: "¿Qué imprime printf(\"Resultado: %.2f\", 10.0 / 3)?",
      opts: ["Resultado: 3", "Resultado: 3.33", "Resultado: 3.3333", "Resultado: 3.333333"], correct: 1,
      exp: "%.2f formatea con 2 decimales. 10.0 / 3 = 3.333... → se muestra como 3.33." },
    { q: "¿Cuál es el tipo de retorno correcto para un método que calcula el promedio de dos enteros?",
      opts: ["int", "void", "double", "String"], correct: 2,
      exp: "El promedio puede ser decimal, así que double es el tipo de retorno adecuado para no perder precisión." },
  ]},
  { topicId: 31, title: "Desafíos Finales", questions: [
    { q: "¿Qué estructura se usa para imprimir un triángulo de asteriscos de n filas?",
      opts: ["Un solo bucle for", "Bucles anidados (for dentro de for)", "Un bucle while con acumulador", "Un array de Strings"], correct: 1,
      exp: "Para imprimir un patrón bidimensional se necesitan bucles anidados: el externo controla las filas, el interno los asteriscos por fila." },
    { q: "Para calcular el promedio de notas en un array, ¿qué se necesita?",
      opts: ["Ordenar el array primero", "Sumar todos los elementos y dividir por la cantidad", "Usar Arrays.sort()", "Convertir las notas a String"], correct: 1,
      exp: "El promedio es la suma de todos los valores dividida por la cantidad. Se acumula recorriendo el array y se divide por array.length." },
    { q: "¿Qué operador se usa para verificar si un número es par?",
      opts: ["/ 2 == 0", "% 2 == 0", "* 2 == 0", "// 2 == 0"], correct: 1,
      exp: "n % 2 == 0 es la forma estándar: si el resto de dividir por 2 es 0, el número es par." },
    { q: "Para contar cuántos valores en un array son mayores a 60, ¿qué se necesita?",
      opts: ["Arrays.sort() y buscar desde el final", "Un bucle con un if y un contador", "Dos bucles anidados", "Convertir el array a String"], correct: 1,
      exp: "Se recorre el array con un bucle for-each, y dentro se verifica con if si el elemento > 60; en ese caso se incrementa un contador." },
    { q: "¿Qué método de la clase Math devuelve el mayor de dos enteros?",
      opts: ["Math.max(a, b)", "Math.min(a, b)", "Math.abs(a)", "Math.pow(a, b)"], correct: 0,
      exp: "Math.max(a, b) devuelve el mayor de los dos valores. Está disponible sin import porque Math pertenece a java.lang." },
  ]},
];

module.exports = { QUIZZES };
